### PR TITLE
Fix mutable requests array #1

### PR DESCRIPTION
**Pull request by oshliaer**
Regarding #1 

It seems the main loop is based on execution the requests array via splices
- https://github.com/tanaikech/BatchRequest/blob/dcef189de873a02d416156f8d460bf33c3a9faa2/BatchRequests.js#L70
- https://github.com/tanaikech/BatchRequest/blob/dcef189de873a02d416156f8d460bf33c3a9faa2/BatchRequests.js#L90

This PR make a deep copy of the requests array before anything.

### CODE REVIEW

**Comment by tanaikech** [comment]
Thank you for your suggestion. 

About `It seems the main loop is based on execution the requests array via splices`, in the method of `EDo()`, the requests more than 100 can be processed. For this, `splice` is used. When `splice` is used at Google Apps Script, the memory can be saved.

Can I ask you about `a deep copy of the requests array before anything.`?

And, in the current stage, this library doesn't use V8. Because this had released before V8 runtime is released. Of course, recently, when I release a GAS library, I use V8 runtime. How do you think about this?

If I misunderstood your suggestion, I apologize.

**Comment by oshliaer** [comment]
Thanks for your comments.

It seems the shallow copy is fine for this.

I replaced this for Rhino. I also added the full sample to #1.

**Comment by tanaikech** [comment]
Thank you for replying. I confirmed it. About `p_.requests`, I would like to agree with using the call by value instead of the call by reference.

**Comment by tanaikech** [comment]
This GAS library was published as v1.1.4.

**Pull request merged**
